apiVersion: apps/v1

kind: Deployment

metadata:
  name: vprodb #name of the deployment
  labels:
    app: vprodb

spec:
  selector:
    matchLabels: #any pod with the below label will already be considered in this deployment
      app:Vprodb
  replicas: 1
  template:
    metadata:
      labels:
        app: vprodb
    spec:
      containers:
        - name: vprodb
          image: afzaalahmedkhan/vprofiledb
          ports:
            - name: vprodb-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                SecretKeyRef:
                  name: app-secret
                  key: db-pass
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: vprodb-data
      nodeSelector:
        zone: us-east-1a
      volumes:
        - name: vprodb-data
          awsElasticBlockStore:
            volumeId: vol-08224a86038fda58c
            fsType: ext4
      initContainers:
        - name: myinit
          image: busybox:latest
          args: ["rm" , "-rf", "/var/lib/mysql/lost+found"]
          volumeMounts:
            - name: vprodb-data
              mountPath: /var/lib/mysql








          
